### ISSUE TITLE
MISSING on  Package Control

### ISSUE THREAD

**Issue by utensil** [jzelenkov/sublime-railscasts-extended#27]
![image](https://cloud.githubusercontent.com/assets/64258/7448868/387820b2-f258-11e4-9b6d-e69f551984e7.png)

**Comment by utensil** [comment]
I believe this is because you have renamed your Github account from jzelenkov to @jevzee 2 days ago?

**Comment by jayzelenkov** [comment]
You're right. My guess is that it took package control some time to re-index repositories. Works now: https://packagecontrol.io/packages/Railscasts%20Extended

**Comment by utensil** [comment]
:+1:
